// <auto-generated />
namespace SocialNetwork.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class db_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201310311947410_db_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
