//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialNetwork.Web.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О себе.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деятельность.
        /// </summary>
        public static string Activies {
            get {
                return ResourceManager.GetString("Activies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина email должна быть от 3 до 100 символов.
        /// </summary>
        public static string AllowedLengthEmail {
            get {
                return ResourceManager.GetString("AllowedLengthEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина фамилии должна быть от 3 до 100 символов.
        /// </summary>
        public static string AllowedLengthLastName {
            get {
                return ResourceManager.GetString("AllowedLengthLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина отчества должна быть до 100 символов.
        /// </summary>
        public static string AllowedLengthMiddleName {
            get {
                return ResourceManager.GetString("AllowedLengthMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина имени должна быть от 3 до 100 символов.
        /// </summary>
        public static string AllowedLengthName {
            get {
                return ResourceManager.GetString("AllowedLengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше фото.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли должны совпадать.
        /// </summary>
        public static string ComparePasswords {
            get {
                return ResourceManager.GetString("ComparePasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий город.
        /// </summary>
        public static string CurrentCity {
            get {
                return ResourceManager.GetString("CurrentCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить данные.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка входа.
        /// </summary>
        public static string ErrorEnterence {
            get {
                return ResourceManager.GetString("ErrorEnterence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким email уже зарегистрирован.
        /// </summary>
        public static string ExistEmail {
            get {
                return ResourceManager.GetString("ExistEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любимые книги.
        /// </summary>
        public static string FavoriteBooks {
            get {
                return ResourceManager.GetString("FavoriteBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любимые игры.
        /// </summary>
        public static string FavoriteGames {
            get {
                return ResourceManager.GetString("FavoriteGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любимые фильмы.
        /// </summary>
        public static string FavoriteMovies {
            get {
                return ResourceManager.GetString("FavoriteMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любимая музыка.
        /// </summary>
        public static string FavoriteMusic {
            get {
                return ResourceManager.GetString("FavoriteMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любимые цытаты.
        /// </summary>
        public static string FavoriteQuotes {
            get {
                return ResourceManager.GetString("FavoriteQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друзья.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гость.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интересы.
        /// </summary>
        public static string Interests {
            get {
                return ResourceManager.GetString("Interests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить?.
        /// </summary>
        public static string IsRemember {
            get {
                return ResourceManager.GetString("IsRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Network.
        /// </summary>
        public static string MainName {
            get {
                return ResourceManager.GetString("MainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобильный телефон.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моя страница.
        /// </summary>
        public static string MyPage {
            get {
                return ResourceManager.GetString("MyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите, пожалуйста, вашу дату рождения.
        /// </summary>
        public static string NoBirthday {
            get {
                return ResourceManager.GetString("NoBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите, пожалуйста, введенный пароль.
        /// </summary>
        public static string NoConfirmPass {
            get {
                return ResourceManager.GetString("NoConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите, пожалуйста, ваш email.
        /// </summary>
        public static string NoEmail {
            get {
                return ResourceManager.GetString("NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите, пожалуйста, вашу фамилию.
        /// </summary>
        public static string NoLastName {
            get {
                return ResourceManager.GetString("NoLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите, пожалуйста, ваше имя.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите, пожалуйста, пароль.
        /// </summary>
        public static string NoPass {
            get {
                return ResourceManager.GetString("NoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите ваш пол.
        /// </summary>
        public static string NoSex {
            get {
                return ResourceManager.GetString("NoSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат даты введен не верно.
        /// </summary>
        public static string NoValidDate {
            get {
                return ResourceManager.GetString("NoValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email имеет неверный формат.
        /// </summary>
        public static string NoValidEmail {
            get {
                return ResourceManager.GetString("NoValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не соответствует заданным критериям надежности.
        /// </summary>
        public static string NoValidPass {
            get {
                return ResourceManager.GetString("NoValidPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий пароль не верный.
        /// </summary>
        public static string OldPasswordNotCorrect {
            get {
                return ResourceManager.GetString("OldPasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обзор пользователей.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Придумайте себе пароль - он должен содержать как минимум один букву верхнего регистра, одну нижнего, одну цифру, один специальный символ и не должен содержать пробелов. Допустимая длина пароль - от 6 до 18 символов.
        /// </summary>
        public static string RequiredPass {
            get {
                return ResourceManager.GetString("RequiredPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так, попробуйте еще раз....
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком длинное название....
        /// </summary>
        public static string TooManySymbols {
            get {
                return ResourceManager.GetString("TooManySymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сайт.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша страница.
        /// </summary>
        public static string YourPage {
            get {
                return ResourceManager.GetString("YourPage", resourceCulture);
            }
        }
    }
}
